name: inject-test

on:
  pull_request:
    types: [opened, edited]

jobs:
  echo-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR title without quotes (vulnerable)
        run: |
          echo PR Title is:
          eval ${{ github.event.pull_request.title }}
